### ISSUE TITLE
Database Creation

### ISSUE THREAD

**Issue by carducci000** [carducci000/Learning#1]
As an organization, a database is desired in order to support the saving/persisting of data.

In SSMS create a new database under databases called KUDB
Create a new table within the database called CLASSES
The table structure should have the following columns:

- [x] ClassId - BigInt
- [x] ClassName - Varchar(250)
- [x] ClassDescription - Varchar(500) - Allow Nulls
- [x] Instructor - Varchar(50) - Allow Nulls
- [x] StartDate - DateTime  - Allow Nulls
- [x] EndDate - DateTime  - Allow Nulls
- [x] Grade - Char(1)   - Allow Nulls

Save the table.

**Comment by GabeCarducci** [comment]
@carducci000 I finished the assignment.

**Comment by carducci000** [comment]
@GabeCarducci  - please ensure to attach create scripts for just the database as well as the Table Script.  Always attack scripts

**Comment by carducci000** [comment]
@GabeCarducci  - when you are done with your tasks, and QA (testing) has signed off on it (in this case, verbally), you can CLOSE the task below - add a comment (anything you wish, but something useful like "database object created successfully".

**Comment by carducci000** [comment]
@GabeCarducci - when you are done with your tasks, and QA (testing) has signed off on it (in this case, verbally), you can CLOSE the task below - add a comment (anything you wish, but something useful like "database object created successfully".

**Comment by carducci000** [comment]
@GabeCarducci - when you are done with your tasks, and QA (testing) has signed off on it (in this case, verbally), you can CLOSE the task below - add a comment (anything you wish, but something useful like "database object created successfully".

**Comment by GabeCarducci** [comment]
@carducci000 
[kudb table script.txt](https://github.com/carducci000/Learning/files/13707369/kudb.table.script.txt)
[KUDBScript.txt](https://github.com/carducci000/Learning/files/13707370/KUDBScript.txt)
Scripts created for the database and table.

**Comment by carducci000** [comment]
@GabeCarducci  please close this task with comment
