### ISSUE TITLE
Create Account for Authentication Platform

### ISSUE THREAD

**Issue by carducci000** [carducci000/Learning#2]
You will be prompted to log into the account:

https://manage.auth0.com/invite?token=YndjaFdCWFg3QWs1ZTJMajpjYXJkdWNjaW5ldHdvcmtAcHJvZC11cy00

Go to link and create a password for yourself and log on.  This is an oAuth Authentication Platform.  I'm going to teach you all about it with our new website.

@GabeCarducci

**Comment by GabeCarducci** [comment]
Created an account for myself
