### ISSUE TITLE
Upgrade Visual Studio to the latest Version 

### ISSUE THREAD

**Issue by carducci000** [carducci000/Learning#3]
There is an UPGRADE WIZARD in the ABOUT menu of Visual STudio.  Upgrade to the latest version

**Comment by carducci000** [comment]
You won't be able to even use the .NET 7 SDK until you finish this task.  Version below 17.8 won't recognize it, so we can use the .net 7 templates with .net 7 core sdk until this is upgraded.

**Comment by GabeCarducci** [comment]
I upgraded to latest version
