### ISSUE TITLE
Install Auth0 templates for Visual Studio for Blazor

### ISSUE THREAD

**Issue by carducci000** [carducci000/Learning#5]
https://auth0.com/blog/introducing-auth0-templates-for-dotnet/

Visit this site to follow the instructions for installing Visual Studio templates for Blazor by Auth0.

Ask questions or please update in comments when you are running into issues.

**Comment by carducci000** [comment]
FYI, visual studio templates are basically starter templates for creating new websites or web api's.  They help you get off the ground quickly with making websites.  These are being installed for a specific reason

**Comment by carducci000** [comment]
I forgot.  For these templates you will need .net core 7 sdk, not 8.  Leave 8 on, but also install this one:

https://dotnet.microsoft.com/en-us/download/visual-studio-sdks

7 sdk, also x64

![image](https://github.com/carducci000/Learning/assets/10613838/182297fc-2205-4966-963f-7559cfd9d4d8)

**Comment by carducci000** [comment]
then you can close this.

**Comment by GabeCarducci** [comment]
Downloaded everything listed
