### ISSUE TITLE
Create an Auth0 Application

### ISSUE THREAD

**Issue by carducci000** [carducci000/Learning#6]
I want to build a website. When I do, I want the website users to be able to log in and access my site with token-based Authentication. 
 
In order to build a website with authentication, I first need to create an 'Application' in Auth0 that my website will link to when authenticating.  

**To do this, go to** 

https://manage.auth0.com/dashboard/us/carduccinetwork/applications

**click on CREATE APPLICATION**

For NAME: <ENTER YOUR APP NAME>

**Choose type of Application:  SINGLE PAGE APPLICATION**

Once Created, go into your new application.  Copy the ClientID, and Domain.  You will need these for your new website.

**Comment by GabeCarducci** [comment]
Created the application named Gabe's Website

**Comment by carducci000** [comment]
@GabeCarducci  - never use an apostrophe if you can help it.  Can you go remove those from your api and application?
