### ISSUE TITLE
Create an Auth0 API also

### ISSUE THREAD

**Issue by carducci000** [carducci000/Learning#7]
Along with story https://github.com/carducci000/Learning/issues/6, I will want to create an Auth0 Api.

The API is used by your website after Authentication.  

Once a user logs into your website, as they navigate through the site (already logged in), their cookie that contains their Authentication Token will occasionally call back to Auth0 to make sure the cookie token is valid.  It does this through the API Audience.  So here's how to make it:

1. Navigate to the Auth0 Api's page: https://manage.auth0.com/dashboard/us/carduccinetwork/apis
2. Click on CREATE API
3. Give is a Name (try to keep it similar to Story 6's Application Name.  I typically would do "<ApplicationName> API"
4. For the Identifier (this is the Audience), it can be anything.  The typical Identifier would be the URL of your website that calls it + "/api/v1".  So an example for mine is "https://localhost:23525/api/v1" but you can put in whatever you like for now.
5. Signing Algorithm is the encryption level all calls will use.  RS256 is fine (the default).
6. Hit CREATE and you're done.
7. Go into the Api once created and copy the Identifier you just made (Audience).

**Comment by carducci000** [comment]
So your values are as follows:

Domain: "carduccinetwork.us.auth0.com",
Authority: "https://carduccinetwork.us.auth0.com",
Audience: <PASTE YOUR AUDIENCE HERE>
ClientId:  <FROM YOUR WEBSITE in Auth0 (story6)>
Audience: <AUDIENCE from ISSUE 7 - this story>

you will need these when you are creating your new website (coming up).

**Comment by GabeCarducci** [comment]
API created

**Comment by carducci000** [comment]
@GabeCarducci - never use an apostrophe if you can help it. Can you go remove those from your api and application?
